# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jevdee's blog
tagline:          'AAA Jekyll theme'
description:      'test'
url:              https://jevdee.github.io
baseurl:          '/'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
remote_theme : poole/hyde
